// Generated by LiveScript 1.5.0
(function(){
  var requireLs, load, ref$, map, concat, groupBy, objToPairs, sortBy, take, reverse, _, command, length;
  requireLs = require('require-ls');
  load = require('./load.ls');
  ref$ = require('prelude-ls'), map = ref$.map, concat = ref$.concat, groupBy = ref$.groupBy, objToPairs = ref$.objToPairs, map = ref$.map, sortBy = ref$.sortBy, take = ref$.take, reverse = ref$.reverse;
  ref$ = process.argv, _ = ref$[0], _ = ref$[1], command = ref$[2], length = ref$[3];
  load('participants', function(err, items){
    var rating, this$ = this;
    return rating = take(length)(
    reverse(
    sortBy(function(it){
      return it[1];
    })(
    map(function(it){
      return [it[0], it[1].length];
    })(
    objToPairs(
    groupBy(function(it){
      return it[0];
    })(
    concat(
    map(function(it){
      return it.holders;
    })(
    items))))))));
  });
}).call(this);
