// Generated by LiveScript 1.5.0
(function(){
  var requireLs, load, ref$, _, command, length;
  requireLs = require('require-ls');
  load = require('./load.ls');
  ref$ = process.argv, _ = ref$[0], _ = ref$[1], command = ref$[2], length = ref$[3];
  load('participants', function(err, items){
    return console.log(items);
  });
}).call(this);
